### ISSUE TITLE
Path to Stage 4!

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-get-intrinsic#1]
## Stage 4
 - [ ] committee approval
 - [ ] two implementations
 - [ ] significant in-the-field experience
 - [ ] ecma262 PR approved
 - [ ] prepare ecma262 PR
 - [ ] merge test262 tests
 - [ ] write test262 tests

## Stage 3
 - [ ] committee approval
 - [ ] spec editor signoff
 - [ ] spec reviewer signoff
 - [ ] receive implementor feedback

## Stage 2
 - [x] incorporate enumeration (#17)
 - [ ] answer open questions
   - [x] #6
   - [x] #5
   - [x] #4
   - [x] #3
   - [x] #19
   - [x] #20
   - [ ] #21
 - [ ] committee approval
 - [ ] spec reviewers selected
 - [ ] spec text written

## ~Stage 1~
 - [x] committee approval
